name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip list

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcloud-key.json

      - name: Download required files
        run: |
          mkdir -p data/processed
          mkdir -p models

          if [ ! -f data/processed/test_processed.csv ]; then
            echo "Downloading test_processed.csv..."
            gsutil cp gs://<your-bucket-name>/data/processed/test_processed.csv data/processed/test_processed.csv
          else
            echo "File data/processed/test_processed.csv already exists. Skipping download."
          fi

          if [ ! -f models/price_model.pth ]; then
            echo "Downloading price_model.pth..."
            gsutil cp gs://<your-bucket-name>/models/price_model.pth models/price_model.pth
          else
            echo "File models/price_model.pth already exists. Skipping download."
          fi

      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m
